version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-host
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abhi
      MYSQL_DATABASE: feedback_app
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data1:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feedback1

  node:
    build: .
    container_name: feedback_app
    environment:
      MYSQL_HOST: mysql-host
      MYSQL_USER: root
      MYSQL_PASSWORD: abhi   # <-- fixed this line
      MYSQL_DATABASE: feedback_app
    ports:
      - "5000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - feedback1

networks:
  feedback1:
    driver: bridge

